# Defines the services (containers) that make up your application.
services:
  # The Python backend service
  backend:
    # Tells Docker Compose to build the image from the 'backend' directory
    build: ./backend
    # Maps port 5000 on the host to port 5000 in the container
    ports:
      - "5000:5000"
    # Mounts host directories into the container for development and data persistence
    volumes:
      # Mounts the backend's source code for live-reloading during development
      - ./backend:/app
      # Creates and mounts a named volume to persist the SQLite database
      # This ensures your data is saved even if the container is removed.
      - sqlite_data:/app/data
    # Renames the container for easier identification
    container_name: fastnote-backend

  # The React frontend service
  frontend:
    # Tells Docker Compose to build the image from the 'frontend' directory
    build: ./frontend
    # Maps port 3000 on the host to port 3000 in the container
    ports:
      - "3000:3000"
    # Mounts the frontend's source code directory for hot-reloading
    volumes:
      - ./frontend:/app
      # Prevents node_modules from being overwritten by the host's node_modules
      - /app/node_modules
    # Renames the container
    container_name: fastnote-frontend
    # Ensures the backend service is started before the frontend
    depends_on:
      - backend

# Defines the named volume for persisting the database
volumes:
  sqlite_data: