from app.extensions import db
import datetime
import uuid

class Note(db.Model):
    __tablename__ = 'notes'
    
    # CHANGED: Now uses UUIDs generated by the frontend (or backend fallback)
    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    title = db.Column(db.String(255), nullable=False)
    content = db.Column(db.Text, nullable=True) # Text or String depending on what you used
    type = db.Column(db.String(50), nullable=False, default='markdown')
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    
    # NEW: Critical for Last-Write-Wins conflict resolution
    updated_at = db.Column(db.DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    def to_dict(self):
        return {
            'id': self.id,
            'title': self.title,
            'content': self.content,
            'type': self.type,
            'updated_at': self.updated_at.isoformat() + 'Z' if self.updated_at else None
        }